name: codemagic_app_preview
packages:
  - "packages/**"
repository: https://github.com/nilsreichardt/codemagic-app-preview

scripts:
  analyze:
    run: melos exec -- "flutter analyze --fatal-infos"
    description: Run `flutter analyze --fatal-infos` in all packages

  format:
    run: melos exec -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  test:
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run `flutter test` in all packages
