name: codemagic_app_preview
packages:
  - "packages/**"
repository: https://github.com/nilsreichardt/codemagic-app-preview

scripts:
  analyze:
    run: melos run analyze:dart --no-select && melos run analyze:flutter --no-select
    description: Run `dart analyze` & `flutter analyze` in all packages

  analyze:dart:
    description: Run `dart analyze --fatal-infos` in all packages
    exec: dart analyze --fatal-infos
    packageFilters:
      flutter: false

  analyze:flutter:
    description: Run `flutter analyze --fatal-infos` in all packages
    exec: flutter analyze --fatal-infos
    packageFilters:
      flutter: true

  format:
    run: |
      prettier . --write
      melos exec -- "dart format . --set-exit-if-changed"
    description: Run `dart format .` in all packages

  test:
    run: melos exec --dir-exists=test -- "dart test"
    description: Run `dart test` in all packages

  # Run `export GITHUB_TOKEN=...` before using this command.
  test-e2e:
    run: |
      cd packages/codemagic_app_preview
      dart --define=GITHUB_TOKEN=$GITHUB_TOKEN \
        --define=GITLAB_TOKEN=$GITLAB_TOKEN \
        --define=CODEMAGIC_TOKEN=$CODEMAGIC_TOKEN \
        test integration_test \
        --use-data-isolate-strategy
