name: codemagic_app_preview
packages:
  - "packages/**"
repository: https://github.com/nilsreichardt/codemagic-app-preview

scripts:
  analyze:
    run: melos exec -- "flutter analyze --fatal-infos"
    description: Run `flutter analyze --fatal-infos` in all packages

  format:
    run: melos exec -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  test:
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run `flutter test` in all packages

  # Run `export GITHUB_TOKEN=...` before using this command.
  test-e2e:
    run: |
      cd packages/codemagic_app_preview
      dart --define=GITHUB_TOKEN=$GITHUB_TOKEN \
        --define=GITLAB_TOKEN=$GITLAB_TOKEN \
        --define=CODEMAGIC_TOKEN=$CODEMAGIC_TOKEN \
        test integration_test \
        --use-data-isolate-strategy
