name: app_preview_example
description: An example project to demonstrate the use of the codemagic_app_preview package.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  app_preview_lints:
    path: ../app_preview_lints

flutter:
  uses-material-design: true
