name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

env:
  FLUTTER_VERSION: 2.5.0 # Uses Dart SDK v2.14.0
  DART_VERSION: 2.14.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run: melos bootstrap

      - name: Run tests
        run: melos run test

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run: melos bootstrap

      - name: Run analyze
        run: melos run analyze

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run: melos bootstrap

      - name: Run format
        run: melos run format

  pana:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/codemagic_app_preview
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install pana
        run: dart pub global activate pana

      - name: Install dependencies
        run: dart pub get

      - name: Verify Pub Score
        run: pana --exit-code-threshold 0

  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
